In [1]:
import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from rasterstats import zonal_stats

In [30]:
gdf_road=gpd.read_file('road.geojson')

In [4]:
pois_public_service=pd.read_csv('pois_public_service.csv')

In [5]:
pois_public_service

,Unnamed: 0,parent,distance,keytag,importance,biz_ext,type,photos,building,typecode,...,pname,biz_type,cityname,childtype,atag,name,location,shopid,favorite_num,featured_reviews
0,0,[],[],三甲医院,[],"{'cost': [], 'opentime2': '周一至周五 08:00-17:30,1...",医疗保健服务;综合医院;三级甲等医院,"[{'title': [], 'url': 'https://aos-comment.ama...",[],090101,...,广东省,[],广州市,[],[],广东省中医院(大德路总院),"113.256541,23.118233",[],[],[]
1,1,[],[],三甲医院,[],"{'cost': [], 'opentime2': '周一至周日 08:00-12:00,1...",医疗保健服务;综合医院;三级甲等医院,"[{'title': [], 'url': 'http://store.is.autonav...",[],090101,...,广东省,[],广州市,[],[],中山大学附属第一医院,"113.291007,23.126383",[],[],[]
2,2,[],[],三甲医院,[],"{'cost': [], 'opentime2': '周一至周五 09:00-21:00',...",医疗保健服务;综合医院;三级甲等医院,"[{'title': [], 'url': 'https://aos-comment.ama...",[],090101,...,广东省,[],广州市,[],[],广东省中医院大学城医院,"113.389822,23.047395",[],[],[]
3,3,[],[],三甲医院,[],"{'cost': [], 'opentime2': '周一至周五 08:00-12:00,1...",医疗保健服务;综合医院;三级甲等医院,"[{'title': [], 'url': 'http://store.is.autonav...",[],090101,...,广东省,[],广州市,[],[],广州医科大学附属第一医院(沿江路总院),"113.262124,23.112649",[],[],[]
4,4,[],[],三甲医院,[],"{'cost': [], 'opentime2': '周一至周日 07:00-17:00',...",医疗保健服务;综合医院;三级甲等医院,"[{'title': [], 'url': 'https://aos-comment.ama...",[],090101,...,广东省,[],广州市,[],[],广东省人民医院,"113.287272,23.125087",[],[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2165,2199,[],[],公厕,[],"{'cost': [], 'opentime2': '周一至周日 00:00-24:00',...",公共设施;公共厕所;公共厕所,"[{'title': [], 'url': 'https://aos-comment.ama...",[],200300,...,广东省,[],广州市,[],[],公共厕所,"113.244598,23.210434",[],[],[]
2166,2200,[],[],公厕,[],"{'cost': [], 'opentime2': [], 'rating': [], 'o...",公共设施;公共厕所;公共厕所,"[{'title': [], 'url': 'http://store.is.autonav...",[],200300,...,广东省,[],广州市,[],[],公共厕所,"113.373849,23.078248",[],[],[]
2167,2201,B00140BDKA,[],公厕,[],"{'cost': [], 'opentime2': [], 'rating': [], 'o...",公共设施;公共厕所;公共厕所,"[{'title': [], 'url': 'http://store.is.autonav...",[],200300,...,广东省,[],广州市,321,[],公共厕所,"113.606242,23.121422",[],[],[]
2168,2202,[],[],公厕,[],"{'cost': [], 'opentime2': [], 'rating': [], 'o...",公共设施;公共厕所;公共厕所,"[{'title': [], 'url': 'http://store.is.autonav...",[],200300,...,广东省,[],广州市,[],[],公共厕所,"113.292785,23.119468",[],[],[]
2169,2203,B0I1PGLH37,[],公厕,[],"{'cost': [], 'opentime2': '周一至周日 00:00-24:00',...",公共设施;公共厕所;公共厕所,"[{'title': [], 'url': 'http://store.is.autonav...",[],200300,...,广东省,[],广州市,302,[],石桥公园公共厕所,"113.362548,22.950789",[],[],[]

In [6]:
location=pois_public_service['location'].str.split(',',expand=True)

In [7]:
location.rename(columns={0:'longitude'},inplace=True)
location.rename(columns={1:'latitude'},inplace=True)

In [8]:
pois_public_service=pois_public_service.join(location,how='outer')

In [9]:
pois_public_service

,Unnamed: 0,parent,distance,keytag,importance,biz_ext,type,photos,building,typecode,...,cityname,childtype,atag,name,location,shopid,favorite_num,featured_reviews,longitude,latitude
0,0,[],[],三甲医院,[],"{'cost': [], 'opentime2': '周一至周五 08:00-17:30,1...",医疗保健服务;综合医院;三级甲等医院,"[{'title': [], 'url': 'https://aos-comment.ama...",[],090101,...,广州市,[],[],广东省中医院(大德路总院),"113.256541,23.118233",[],[],[],113.256541,23.118233
1,1,[],[],三甲医院,[],"{'cost': [], 'opentime2': '周一至周日 08:00-12:00,1...",医疗保健服务;综合医院;三级甲等医院,"[{'title': [], 'url': 'http://store.is.autonav...",[],090101,...,广州市,[],[],中山大学附属第一医院,"113.291007,23.126383",[],[],[],113.291007,23.126383
2,2,[],[],三甲医院,[],"{'cost': [], 'opentime2': '周一至周五 09:00-21:00',...",医疗保健服务;综合医院;三级甲等医院,"[{'title': [], 'url': 'https://aos-comment.ama...",[],090101,...,广州市,[],[],广东省中医院大学城医院,"113.389822,23.047395",[],[],[],113.389822,23.047395
3,3,[],[],三甲医院,[],"{'cost': [], 'opentime2': '周一至周五 08:00-12:00,1...",医疗保健服务;综合医院;三级甲等医院,"[{'title': [], 'url': 'http://store.is.autonav...",[],090101,...,广州市,[],[],广州医科大学附属第一医院(沿江路总院),"113.262124,23.112649",[],[],[],113.262124,23.112649
4,4,[],[],三甲医院,[],"{'cost': [], 'opentime2': '周一至周日 07:00-17:00',...",医疗保健服务;综合医院;三级甲等医院,"[{'title': [], 'url': 'https://aos-comment.ama...",[],090101,...,广州市,[],[],广东省人民医院,"113.287272,23.125087",[],[],[],113.287272,23.125087
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2165,2199,[],[],公厕,[],"{'cost': [], 'opentime2': '周一至周日 00:00-24:00',...",公共设施;公共厕所;公共厕所,"[{'title': [], 'url': 'https://aos-comment.ama...",[],200300,...,广州市,[],[],公共厕所,"113.244598,23.210434",[],[],[],113.244598,23.210434
2166,2200,[],[],公厕,[],"{'cost': [], 'opentime2': [], 'rating': [], 'o...",公共设施;公共厕所;公共厕所,"[{'title': [], 'url': 'http://store.is.autonav...",[],200300,...,广州市,[],[],公共厕所,"113.373849,23.078248",[],[],[],113.373849,23.078248
2167,2201,B00140BDKA,[],公厕,[],"{'cost': [], 'opentime2': [], 'rating': [], 'o...",公共设施;公共厕所;公共厕所,"[{'title': [], 'url': 'http://store.is.autonav...",[],200300,...,广州市,321,[],公共厕所,"113.606242,23.121422",[],[],[],113.606242,23.121422
2168,2202,[],[],公厕,[],"{'cost': [], 'opentime2': [], 'rating': [], 'o...",公共设施;公共厕所;公共厕所,"[{'title': [], 'url': 'http://store.is.autonav...",[],200300,...,广州市,[],[],公共厕所,"113.292785,23.119468",[],[],[],113.292785,23.119468
2169,2203,B0I1PGLH37,[],公厕,[],"{'cost': [], 'opentime2': '周一至周日 00:00-24:00',...",公共设施;公共厕所;公共厕所,"[{'title': [], 'url': 'http://store.is.autonav...",[],200300,...,广州市,302,[],石桥公园公共厕所,"113.362548,22.950789",[],[],[],113.362548,22.950789

In [15]:
crs_proj = "EPSG:32650"  
crs_wgs84 = "EPSG:4326"

In [13]:
from shapely.geometry import Point

In [14]:
geometry=[Point(xy)for xy in zip(pois_public_service['longitude'],pois_public_service['latitude'])]

In [16]:
gdf_pois_public_service=gpd.GeoDataFrame(pois_public_service,geometry=geometry,crs=crs_wgs84)

In [27]:
gdf_pois_public_service=gdf_pois_public_service[['id','name','typecode','adname','distance','geometry']]

In [28]:
gdf_pois_public_service

,id,name,typecode,adname,distance,geometry
0,B00140U136,广东省中医院(大德路总院),090101,越秀区,[],POINT (113.25654 23.11823)
1,B00140226E,中山大学附属第一医院,090101,越秀区,[],POINT (113.29101 23.12638)
2,B00140TVLT,广东省中医院大学城医院,090101,番禺区,[],POINT (113.38982 23.0474)
3,B00141SV1C,广州医科大学附属第一医院(沿江路总院),090101,越秀区,[],POINT (113.26212 23.11265)
4,B00140UERJ,广东省人民医院,090101,越秀区,[],POINT (113.28727 23.12509)
...,...,...,...,...,...,...
2165,B0FFH18OFY,公共厕所,200300,白云区,[],POINT (113.2446 23.21043)
2166,B0FFHLSADA,公共厕所,200300,海珠区,[],POINT (113.37385 23.07825)
2167,B0FFH6UMVL,公共厕所,200300,增城区,[],POINT (113.60624 23.12142)
2168,B00140U4J9,公共厕所,200300,越秀区,[],POINT (113.29278 23.11947)
2169,B0KGS7MC4N,石桥公园公共厕所,200300,番禺区,[],POINT (113.36255 22.95079)

In [29]:
gdf_pois_public_service['adname'].value_counts()

adname
天河区    409
白云区    321
越秀区    296
海珠区    247
番禺区    234
荔湾区    156
黄埔区    152
花都区    126
增城区    107
南沙区     72
从化区     50
Name: count, dtype: int64

In [32]:
gdf_pois_public_service.to_file('gdf_pois_public_service.geojson')